# Generated by Django 5.2 on 2025-05-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriterecipe',
            name='source',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
