# Generated by Django 5.2 on 2025-05-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favoriterecipe_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='uri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
